# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FreeStore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FreeStore

  target 'FreeStoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FreeStoreUITests' do
    # Pods for testing
  end

end
